### ISSUE TITLE
VNC is not working with HostOS anaconda installer

### ISSUE THREAD

**Issue by jrziviani** [open-power-host-os/builds#291]
I'm trying to install **HostOS** using VNC but I'm getting the following error:

```
VNC

Text mode provides a limited set of installation options. It does not offer
custom partitioning for full control over the disk layout. Would you like to use
VNC mode instead?

 1) Start VNC

 2) Use text mode

  Please make your choice from above ['q' to quit | 'c' to continue |
  'r' to refresh]: 1
================================================================================
================================================================================
VNC Password

Please provide VNC password (must be six to eight characters long).
You will have to type it twice. Leave blank for no password

Password: 
Password (confirm): 
19:20:55 Starting VNC...
Traceback (most recent call last):
  File "/sbin/anaconda", line 1206, in <module>
    setupDisplay(anaconda, opts, addon_paths)
  File "/sbin/anaconda", line 711, in setupDisplay
    vncS.startServer()
  File "/usr/lib64/python2.7/site-packages/pyanaconda/vnc.py", line 239, in startServer
    iutil.startX(xvnccommand, output_redirect=self.openlogfile())
  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 233, in startX
    signal.pause()
  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 481, in _sigchld_handler
    _raise_exit_error(exit_statuses)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/iutil.py", line 448, in _raise_exit_error
    raise ExitError(", ".join(exn_message))
pyanaconda.iutil.ExitError: Xvnc exited with status 1
Exception AttributeError: "'NoneType' object has no attribute 'udev_unref'" in <bound method Context.__del__ of <pyudev.core.Context object at 0x7fff8627d690>> ignored
```

Due to the limitation of text mode installation:

> Text mode provides a limited set of installation options. It does not offer custom partitioning for full control over the disk layout

I basically cannot install HostOS in my system because I **must** be sure that some partitions will be **preserved**.

Thanks

<cde:info> Mirrored with LTC bug #158508 </cde:info>

**Comment by cdeadmin** [comment]
------- Comment on attachment From olavph@br.ibm.com 2017-09-15 11:03:47 EDT-------

I've added a missing package to the ISO (metacity) and was able to connect via VNC.
There are still issues with fonts, however, so I'll have to find out what else is missing.
Still working on it.

**Comment by olavph** [comment]
VNC should be working with the ISO from the last build
